services:
    wilhelmsempre.user.token.encoder:
        class: WilhelmSempre\UserBundle\Authorization\Token\Encoder\TokenEncoder

    wilhelmsempre.user.authorization:
        class: WilhelmSempre\UserBundle\Authorization\Authorization